modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Smaller%20Nether%20Portals"
logoFile="icon.png"

[[mods]]
modId="smallernetherportals"
version="3.8"
displayName="Smaller Nether Portals"
displayURL="https://serilum.com/mod/smaller-nether-portals"
authors="Rick South"
description='''Allows the creation of smaller nether portals, specifically 1x2, 1x3 and 2x2.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.smallernetherportals]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.smallernetherportals]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "smallernetherportals.mixins.json"